### ISSUE TITLE
Locale fallbackCode should not be required

### ISSUE THREAD

**Issue by ArondeParon** [contentful/contentful.php#100]
In `ResourceBuilder.php` on line 458, the following code causes an "undefined index" error:

`$locales[] = new Locale($locale['code'], $locale['name'], $locale['fallbackCode'], $locale['default']);`

This is due to the fact that `fallbackCode` does not always exist, in which case, the code should default to something else.

**Comment by realityking** [comment]
Hi Aron,

Thank you for the report. We'd like to take a look at the space, could you please send an email to support@contentful.com referencing this ticket and include the space ID and API key. Thank you!

Cheers,
Rouven

**Comment by ArondeParon** [comment]
done!

**Comment by realityking** [comment]
Closing this as there's been no response to follow up questions. Feel free to reopen it if the issue still occurs.
