### ISSUE TITLE
DeletedEntry should also have a getContentType() method

### ISSUE THREAD

**Issue by Jalle19** [contentful/contentful.php#101]
Currently `DeletedEntry` payloads look like this:

```json
{
  "sys": {
    "type": "DeletedEntry",
    "id": "someid",
    "space": {
      "sys": {
        "type": "Link",
        "linkType": "Space",
        "id": "somespace"
      }
    },
    "revision": 3,
    "createdAt": "2017-05-03T13:19:33.711Z",
    "updatedAt": "2017-05-03T13:19:33.711Z",
    "deletedAt": "2017-05-03T13:19:33.711Z",
    "contentType": {
      "sys": {
        "type": "Link",
        "linkType": "ContentType",
        "id": "theme"
      }
    }
  }
}
```

Yet the `DeletedEntry` class doesn't have the `getContentType()` method that e.g. `DynamicEntry` has. This makes it impossible to determine what type of thing was deleted, you have to parse the raw payload yourself to extract the data.

Are you accepting pull requests? There doesn't seem to be much activity here so I'm reluctant to post a solution myself, but if you acknowledge this then I will.

**Comment by realityking** [comment]
Interesting, how did you get that payload? In the Sync API, this is the result I'm seeing:

```json
{
  "sys": {
    "space": {
      "sys": {
        "type": "Link",
        "linkType": "Space",
        "id": "private"
      }
    },
    "id": "6IAOBpK8x22CqmoYImgmgM",
    "type": "DeletedEntry",
    "createdAt": "2017-05-04T11:34:22.358Z",
    "updatedAt": "2017-05-04T11:34:22.358Z",
    "deletedAt": "2017-05-04T11:34:22.358Z",
    "revision": 1
  }
}
```

**Comment by Jalle19** [comment]
This is from a webhook payload. In general the payloads seem to be identical to what you'd get from the "pull API", but apparently not in this case.

**Comment by realityking** [comment]
Indeed you uncovered the exception to the rule. I'll need to see if we can align them in the API or if we need to implement a workaround in the PHP SDK. Thanks!

**Comment by Jalle19** [comment]
A `HasContentType` trait would probably do the trick here. If a response doesn't include the content type then `getContentType()` could just return null.

Do you want me to PR anything? We'll probably be forking this internally for the time being so we can get around some of these issues.
