### ISSUE TITLE
Undefined index: "fi-FI" (or similar) when attempting to retrieve a non-existing optional property

### ISSUE THREAD

**Issue by Jalle19** [contentful/contentful.php#103]
https://github.com/contentful/contentful.php/blob/master/src/Delivery/DynamicEntry.php#L138 will issue an undefined index notice if you call `$entry->getPartner()` on a `DynamicEntry` made from this piece of JSON:

```json
{
  "sys": {
    "space": {
      "sys": {
        "type": "Link",
        "linkType": "Space",
        "id": "spaceid"
      }
    },
    "type": "Entry",
    "contentType": {
      "sys": {
        "type": "Link",
        "linkType": "ContentType",
        "id": "theme"
      }
    },
    "id": "someid",
    "revision": 3,
    "createdAt": "2017-04-18T12:15:23.567Z",
    "updatedAt": "2017-05-03T11:23:04.368Z"
  },
  "fields": {
    "title": {
      "fi-FI": "Some theme"
    },
    "urlSlug": {
      "fi-FI": "some-theme-slug"
    },
    "category": {
      "fi-FI": {
        "sys": {
          "id": "someid",
          "linkType": "Entry",
          "type": "Link"
        }
      }
    },
    "description": {
      "fi-FI": "Such theme, much something"
    },
    "image": {
      "fi-FI": {
        "sys": {
          "id": "someid",
          "linkType": "Asset",
          "type": "Link"
        }
      }
    },
    "partner": {}
  }
}
```

If ` "partner": {}` is removed, everything works as expected and `getPartner()` will return `NULL`. The `partner` field in this case is an optional non-localized reference.

This effectively means it's impossible to check if a partner has been specified without triggering a notice, which in many cases are converted into exceptions. I filed https://github.com/contentful/contentful.php/issues/102 as a potential workaround for this.

**Comment by Jalle19** [comment]
@realityking same thing with this one, this only happens with the webhook payloads. If I query this particular entry using the CDA the error doesn't happen at all. Hard to tell what's going on since the SDK doesn't expose the raw JSON.

**Comment by realityking** [comment]
I see a pattern here 😄 

Looks like it's time for some proper web hook support, including tests.

**Comment by Jalle19** [comment]
@realityking it wouldn't help per se, but it would make it easier to see the differences. Right now you have to hack the underlying HTTP client or similar to `var_dump()` the raw request.

**Comment by Jalle19** [comment]
@realityking https://support.contentful.com/hc/en-us/requests/16221

**Comment by dborsatto** [comment]
I'm closing this, as per our recent conversation.
