### ISSUE TITLE
Memory exhaustion caused by the buildLink method

### ISSUE THREAD

**Issue by jonchikly** [contentful/contentful.php#105]
The code is stuck in what seems to be an infinite loop which causes a memory exhaustion when getting resources from the resource builder.

The issue seems to come from the **buildLink** method in the ResourceBuilder class (vendor/contentful/contentful/src/Delivery/ResourceBuilder.php)

Commenting out the lines below fix the issue:

```
            if (isset($rawDataList['entry'][$id]) && $depthCount < 20) {
                $depthCount++;
                return $this->buildEntry($rawDataList['entry'][$id], $rawDataList, $depthCount);
            }

```

Is there a fix for that?

**Comment by realityking** [comment]
Thanks for the report @jonchikly. To make it easier to investigate the issue I'd be great if you could send an email to support@contentful.com and include your space ID and API key. Please mention this issue.

I'd also need to know what memory limit is configured in PHP and what query was performed when this happens.

**Comment by realityking** [comment]
Another user has reported the same issue allowing me to reproduce it. The problem seem to happen with very complex content models (many references) that contain a loop in the response. The `$depthCount` check was supposed to guard against this but was obviously not sufficient.

It's unlikely that we'll fix this bug this week. If you're affected please revert back to version 0.6.5, that is the newest version not being affected.

**Comment by jonchikly** [comment]
Great @realityking. Thank you for your feedback. I am following up on this via email.

**Comment by realityking** [comment]
I've created #113 that should fix this issue. I'd be great if you could test if @jonchikly. Thanks you.

**Comment by jonchikly** [comment]
Thank you @realityking. I will have a look and let you know if anything. Have a good day
