### ISSUE TITLE
Grabbing linked content

### ISSUE THREAD

**Issue by graymic** [contentful/contentful.php#11]
Is there a way to actually display "includes" from a request?

Thus far if I have a content entry with references inside, there is no apparent way in which to display these it would seem...

i.e.:

```
$query = new \Contentful\Delivery\Query();
$query->where('include', 3);
$query->where('sys.id', 'someId');
return $client->getEntries($query);
```

or am I going about this incorrectly?

**Comment by realityking** [comment]
Hi Michael,

the PHP SDK allows you access to linked entires simply by accessing the field. For example, if you have a field called `category`, calling `getCategory()` will return the linked entry.

If instead you're trying to list all the entities that are in the `includes` field, that's currently not possible with the PHP SDK. What's your use case for that?

Cheers,
Rouven

**Comment by graymic** [comment]
Suppose I have an entry called Cafe's and in that, I have a further set of references to properties that I consider to be cafe's. Those in turn may have a field of multiple references going to "days of the week" representing opening days.

I want to know how one would query against Cafe's, and be able to see the relationships (The properties related) with the references to the days of the weeks in that.

i.e. 

```
Cafes: [
    Cafe1: [
        Open: [M,T,W,T]
    ], ...
]
```

Is this possible at all?

**Comment by realityking** [comment]
I'm still not sure if I follow you 100%.

In your example, you could access the opening days like this:

```php
foreach ($cafes as $cafe)
{
  var_dump($cafe->getOpen()); // will be an array containing [M,T,W,Th]
}
```

Is this what you're looking for?

**Comment by graymic** [comment]
Yes this could potentially be what I required. Thank you.
