### ISSUE TITLE
Difficulty with query

### ISSUE THREAD

**Issue by carmolim** [contentful/contentful.php#116]
Hello, I want to query all entries of the type "store" that have in the field "category" a link to an specific "id" how can I achieve this?

I tried that: 

```
$query = new \Contentful\Delivery\Query;
$query->setContentType('store')->where('fields.store.pt-BR', $id );
$page = $client->getEntries($query);
```

But didn't work.

**Comment by realityking** [comment]
Hi @carmolim,

I saw you posted the same question on StackOverflow (http://stackoverflow.com/questions/44007647/query-all-entries-of-the-type-store-that-have-in-the-field-category-a-link-t). Was the answer you received there sufficient?

**Comment by realityking** [comment]
Closing this as there's been no response.
