### ISSUE TITLE
DynamicEntry get<FieldName>() returns different data structure in preview client vs published mode

### ISSUE THREAD

**Issue by riyunoa** [contentful/contentful.php#117]
Just did a composer update today, and we noticed that the DynamicEntry get<FieldName>() function is now returning different data formats with the preview client than the normal client. Is there a reason for this?

e.g. in preview 'myField' = [en-US => [en-US => "this value"]
in normal mode 'myField' = [en-US => "this value"]

Is there a way we can get the data in the same format? Thanks!

**Comment by realityking** [comment]
Hi @riyunoa! There's definitely something going wrong here.

Could you please let me know the following things:
* What version of the SDK are you using. (Will be shown if run `composer info contentful/contentful`
* Do you set a locale either when constructing the client or when making the request?

If you have a piece of code that shows the issue, that would be even better. Feel free to send it to support@contentful.com including credentials and mention it's in reference to this ticket and I'll take a look.

**Comment by riyunoa** [comment]
Thanks for your response. We aren't setting the locale when constructing the client or making the request. We actually compared the DynamicEntry.php from the previous version (which returned the same response) and the current version's, and it looks like the `__call(...)` method has changed and is adding in the locale.

Composer details:

    $ composer info contentful/contentful
    name     : contentful/contentful
    descrip. : SDK for the Contentful Content Delivery API
    keywords :
    versions : * 1.2.0
    type     : library
    license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
    source   : [git] https://github.com/contentful/contentful.php.git d3fd015dfe67c9dfdd744ae6531de7c1084d2e4f
    dist     : [zip] https://api.github.com/repos/contentful/contentful.php/zipball/d3fd015dfe67c9dfdd744ae6531de7c1084d2e4f d3fd015dfe67c9dfdd744ae6531de7c1084d2e4f
    names    : contentful/contentful

Constructing the clients:

    $this->contentfulClient = new Client(CmsService::CONTENTFUL_CONTENT_DELIVERY_TOKEN, CmsService::SPACE_ID);

    $this->contentfulPreviewClient = new Client(CmsService::CONTENTFUL_PREVIEW_TOKEN, CmsService::SPACE_ID, true);

Usage:

    if ($previewMode) {
        $content = $this->contentfulPreviewClient->getEntry(CmsService::HOMEPAGE_ENTRY_ID);
    } else {
        $content = $this->contentfulClient->getEntry(CmsService::HOMEPAGE_ENTRY_ID);
    }

    $obj = $content->getBanner(); // <-- returns different response depending on client used

**Comment by riyunoa** [comment]
Actually I think I've found the problem, The preview response contains sys.locale: "en-US", but the cdn response doesn't, when setting the request parameter `locale=*` 

The ResourceBuilder::normalizeFieldData() method sets $locale based on the sys.locale in the response. i.e. In buildEntry(...), `$locale = $sys->getLocale();` This gets passed into buildFields() and then normalizeFieldData()

```
    private function normalizeFieldData($fieldData, $locale)
    {
        if (!$locale) {
            return $fieldData;
        }

        return [$locale => $fieldData];
    }
```

GET https://preview.contentful.com/spaces/cwi48g1va3ut/entries/gZfHi2wu1aYyCEKYq2sKs?access_token=<accesstoken>&locale=*

```
{
  "sys": {
    "space": {
      "sys": {
        "type": "Link",
        "linkType": "Space",
        "id": "cwi48g1va3ut"
      }
    },
    "type": "Entry",
    "id": "gZfHi2wu1aYyCEKYq2sKs",
    "contentType": {
      "sys": {
        "type": "Link",
        "linkType": "ContentType",
        "id": "banner"
      }
    },
    "revision": 86,
    "createdAt": "2017-05-08T06:03:43.323Z",
    "updatedAt": "2017-05-22T01:33:19.623Z",
    "locale": "en-US" <----------------- has locale
  },
  "fields": {
    "bannerUrl": {
      "en-US": "/secure/slide-1.jpg"
    },
    "title": {
      "en-US": "Welcome To Kittens University !!"
    },
    "description": {
      "en-US": "CEO Meow McMeow welcomes you to the new Kittens University.<br>Watch the video to hear Bill's message."
    },
    "link1title": {
      "en-US": "Learn More"
    },
    "link1url": {
      "en-US": "http://www.google.com"
    },
    "link2title": {
      "en-US": null
    },
    "link2url": {
      "en-US": null
    },
    "videoLink": {
      "en-US": "Watch Video"
    },
    "videoUrl": {
      "en-US": "/secure/bill-conner-sw-university-welcome-480p.mp4"
    },
    "videoThumb": {
      "en-US": null
    },
    "videoModalTitle": {
      "en-US": "Welcome to SonicWall University"
    },
    "videoModalSubtitle": {
      "en-US": "Welcome to SonicWall University"
    }
  }
}
```

GET https://cdn.contentful.com/spaces/cwi48g1va3ut/entries/gZfHi2wu1aYyCEKYq2sKs?locale=*&access_token=47d9318a70a660e36e74530b559ad7d9e5ef540ad27b5f9b877099698ac9634d

```
{
  "sys": {
    "space": {
      "sys": {
        "type": "Link",
        "linkType": "Space",
        "id": "cwi48g1va3ut"
      }
    },
    "id": "gZfHi2wu1aYyCEKYq2sKs",
    "type": "Entry",
    "createdAt": "2017-05-08T06:05:35.334Z",
    "updatedAt": "2017-05-22T01:33:19.579Z",
    "revision": 86,
    "contentType": {
      "sys": {
        "type": "Link",
        "linkType": "ContentType",
        "id": "banner"
      }
    }
  },
  "fields": {
    "bannerUrl": {
      "en-US": "/secure/slide-1.jpg"
    },
    "title": {
      "en-US": "Welcome To Kittens University !!"
    },
    "description": {
      "en-US": "CEO Meow McMeow welcomes you to the new Kittens University.<br>Watch the video to hear Bill's message."
    },
    "link1title": {
      "en-US": "Learn More"
    },
    "link1url": {
      "en-US": "http://www.google.com"
    },
    "link2title": {
      "en-US": null
    },
    "link2url": {
      "en-US": null
    },
    "videoLink": {
      "en-US": "Watch Video"
    },
    "videoUrl": {
      "en-US": "/secure/bill-conner-sw-university-welcome-480p.mp4"
    },
    "videoThumb": {
      "en-US": null
    },
    "videoModalTitle": {
      "en-US": "Welcome to SonicWall University"
    },
    "videoModalSubtitle": {
      "en-US": "Welcome to SonicWall University"
    }
  }
}
```

**Comment by realityking** [comment]
Hey @riyunoa, indeed you seem to have uncovered an error in our API itself. I just checked with the backend team, we'll see if we can get a fix for this out soon-ish otherwise I'll try to implement a workaround in the SDK. I'll keep you posted.

**Comment by riyunoa** [comment]
Thank you, we've just rolled back to using version 1.0.0 of the PHP SDK for now.

**Comment by jordanandree** [comment]
@realityking any update on a fix for this? Trying to implement the Preview API and I'm seeing the same inconsistent behavior as @riyunoa

**Comment by realityking** [comment]
@jordanandree We've rolled out the fix to the organizations we use here at Contentful and so far everything has held up. (Check out [this comment](https://github.com/contentful/contentful.php/pull/161#issuecomment-313663972) to learn about how that impacts our integration tests)

Last I heard we'll roll this out to a wider audience by the end of this month. I'll update this when that has happened.

**Comment by jordanandree** [comment]
@realityking Thanks for the quick update on this! Also very good news to hear that it will be updated end of this month.

Also, I'm able to workaround the locale issue by subclassing the `Contentful\Delivery\Client` class and hardcoding a locale in the public `resolveLink` function. This works okay for now since there isn't the need for multiple locales in this context.

Example:
```php
<?php

class CustomClient extends \Contentful\Delivery\Client
{
    public function resolveLink(\Contentful\Link $link, $locale = null)
    {
        if ($this->isPreview()) {
            $locale = "en-US";
        }

        return parent::resolveLink($link, $locale);
    }
}
```

**Comment by beephotography** [comment]
Any news on this issue? It's still now working in our case.
Furthermore, when we try to get an image in preview mode, for example calling `getHeaderImage()`, then the image object has empty values and some notices are thrown.
Thus (since we handle notices like errors) our preview mode is broken. But I'll try to implement @jordanandree 's workaround just for now.

**Comment by dborsatto** [comment]
Hey there,

we're currently still in a testing phase for the fix to the API. Unfortunately because of the nature of the fix, we're just want to take extra precautions. So far, our internal testing yielded positive results, but unfortunately we don't have a firm timeline yet. I'll make sure to update this issue when we have more details 🙂

**Comment by kyllagdrgn** [comment]
I am also have problems with this. I am relived to find out that that there is a fix coming for this. I will be watching for updates

**Comment by zmiKaminski** [comment]
Any update on the release of this fix?  Thanks in advance for all of your help!

**Comment by incraigulous** [comment]
I have also encountered this problem. Looking forward to the fix!

**Comment by kyllagdrgn** [comment]
@dborsatto Are there any updates on this issue

**Comment by dborsatto** [comment]
Hey all,
sorry for keeping silent lately, but now I can finally say we flipped the switch, and now the Preview API should behave as expected. I'll close this issue, but if anything should arise, feel free to continue the discussion!

**Comment by incraigulous** [comment]
Awesome! Thanks!

**Comment by zmiKaminski** [comment]
Thank you!

**Comment by jordanandree** [comment]
@dborsatto thanks!
