### ISSUE TITLE
Where Condition with Linked(Reference Content)

### ISSUE THREAD

**Issue by anandaneesh** [contentful/contentful.php#118]
Hi,

Can I get an example for "Where Condition with Linked(Reference Content)".

Regards,
Aneesh Anand

**Comment by realityking** [comment]
Hi @anandaneesh, 

sorry for the late reply. You can find the docs on this feature here https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/search-on-references if you scroll down a bit and click on "Search on references" you can see some example code, including some using this SDK.

Cheers,
Rouven
