### ISSUE TITLE
buildFile() in ResourceBuilder not getting the correct array if language is set

### ISSUE THREAD

**Issue by beephotography** [contentful/contentful.php#126]
The line
https://github.com/contentful/contentful.php/blob/master/src/Delivery/ResourceBuilder.php#L204

causes that the method buildFile() gets the wrong array.

buildFile() tries to access the array element 'details'

```
        $details = $data['details'];
```

which is available one step deeper in the array. The structure of the array $data in this case is

```
Array
(
    [de-DE] => Array
        (
            [url] => //images.contentful.com/...
            [details] => Array
                (
                    [size] => 4945457
                    [image] => Array
                        (
                            [width] => 6000
                            [height] => 3304
                        )

                )

            [fileName] => 
            [contentType] => image/jpeg
        )
)
```

A possible fix would be to pass the correct array to the buildFile() method, which means to get rid of the first layer of the array like:

```
Array
(
    [url] => //images.contentful.com/.../02979f4779d7c55d9aad665d6a6bfeec/H__hnerei_bearb.jpg
    [details] => Array
        (
            [size] => 4945457
            [image] => Array
                (
                    [width] => 6000
                    [height] => 3304
                )

        )

    [fileName] => 
    [contentType] => image/jpeg
)
```

This works for our case:

```
$normalizedFieldData = $this->normalizeFieldData($fields['file'], $locale);
if ($locale && isset($normalizedFieldData[$locale]) && count($normalizedFieldData[$locale]) > 0) {
    $normalizedFieldData = $normalizedFieldData[$locale];
}
$files = isset($fields['file']) ? array_map([$this, 'buildFile'], $normalizedFieldData) : null;
```

**Comment by realityking** [comment]
`normalizeFieldData` is supposed to take care of exactly that. I'll try to reproduce the issue.

Am I right in thinking you requesting something with `setLocale('*')`?

**Comment by beephotography** [comment]
Hi there,

I forgot to mention that it might have something to do with the $preview parameter set to true.
$defaultLocale parameter has not been set specifically when calling new Client().

**Comment by realityking** [comment]
Ahh, that explains. Unfortunately there's currently a bug in our API that messed with that. We're tracking the problem on the PHP side in #117. I'm closing this, we can continue the conversation over there.
