### ISSUE TITLE
CDN host vs API host 

### ISSUE THREAD

**Issue by tomaszhanc** [contentful/contentful.php#14]
Using PHP SDK for Delivery API I've got an old version of a content. For example in the Contentful a content has a version 20, but from the CDN I've got a version 3. So then when I used that version to use Management API I've got 409 Conflict error with id 'VersionMismatch'. Probably the reason of that is CDN host (cdn.contenful.com) because when I used API host (api.contentful.com) by hand then I've got a correct version of a content.

In the current implementation it's not possible to change the host for API, but maybe it's not necessary and I'm doing something wrong. Can anybody help me with that?

**Comment by realityking** [comment]
Hi Thomas,

I'm not 100% sure what you're trying to do but maybe I can clarify some things:

- This SDK is meant to be used with the Content Delivery API (can.contentful.com) and Preview API (preview.contentful.com). In the future there will be a dedicated SDK for the Content Management API. Unfortunately I don't have a timeline I could share but it will _not_ be soon.

- In the Content Deliver AP you have _only_ access to published content. What you see as `revision` in the CDA is the value of the `publishedCounter` in the CMA, it's _not_ the `version`. But `version` is what you need to control the CMAs locking.

Overall, it's not a good idea to use CDA responses together with the CMA. If you want to manipulate content you should also use the CMA to retrieve the content. Without the PHP SDK that's obviously easier said then done, but you're saving yourself from a world of pain.

Did that help you?

**Comment by tomaszhanc** [comment]
Thanks for a quick response. It's exactly as I thought. Probably the easiest way for me would be to fork the SDK and change the host by hand. I've made a quick test and I think it works. Today I will do more tests to make sure if everything is OK. It will be faster to use the SDK than write everything from the scratch, especially for a nice DataCollector for Symfony Profiler.

**Comment by tomaszhanc** [comment]
@realityking Of course, you're right. It's not so simple to just change a content type, and a host. Have to do it without SDK.
