### ISSUE TITLE
Locale bug noticed

### ISSUE THREAD

**Issue by graymic** [contentful/contentful.php#15]
If you were to set the locale for a field that hasn't got a locale assigned, when using something like say $post->getTitle(), it would yield Undefined property: stdClass::$ru. 

Is there a way of determining if that field has said locale, because if not it would appear the line: 102 in DynamicEntry is the culprit.

Thanks,

Michael

**Comment by realityking** [comment]
Hi Michael,

could you clarify what you mean by "set the locale for a field that hasn't got a locale assigned"? I can't quite understand what you're doing.

Thanks,
Rouven

**Comment by graymic** [comment]
Hey Rouven,

Suppose there is a field within contentful: 'title' which has two locales assigned, Fr and my default En. 

If you were to use the method setLocale to say something like Ru. Because it is not set within contentful the sdk tries to execute against the $locale that doesn't exist resulting in a 500 error. 

This should be caught otherwise you get quite an obscure error, the work around is rather hacky albeit doable though. 

Steps to replicate: 

1. Create a locale for an entry such as title and make Fr available with the default locale being En. 

2. Query against that entry and try and retrieve the title for Fr / En (It will work) with say $entry->getTitle()

3. Query against that entry for a locale that isn't set. It yields, 'Undefined property: stdClass::$ru'
Which is being executed within the DynamicEntry class on line 102. It's a general exception and as such not one being thrown by the contentful sdk.

**Comment by realityking** [comment]
Long time coming on this one. This should now work in current master. Note there are some breaking changes so be careful when you try it. If you still have this problem please reopen this issue.
