### ISSUE TITLE
[Question] How to get a single entry by field value

### ISSUE THREAD

**Issue by rogervila** [contentful/contentful.php#16]
Hello,

As far as I have seen, you can get an entry by its id

```php
$entry = $client->getEntry('entry-id');
```

I have tried to access the fields with the `where` query method this way:

```php
$query = new \Contentful\Delivery\Query;
$query->where('fields.slug', $slug);
$entries = $client->getEntries($query);
```

I have tried with different approaches like `fields.slug.es-ES` but all I get is a 400 Bad Request response, that says that the Content Type ID is required.

My question is: **How can I get a single entry by a field value?**

Thank you.

**Comment by calumbrodie** [comment]
When you are querying using a field, contentful needs to know what content type you are querying, so add the following

`$query->setContentType($contentTypeId);`

If you don't know the content type ID it's the last part of the url, when you are editing/viewing the content type in contentful.

**Comment by rogervila** [comment]
Thank you @calumbrodie 

This is the final query code:

```php
        $client = new \Contentful\Delivery\Client($access, $space);

        $query = new \Contentful\Delivery\Query;

        $query->setContentType('page')->where('fields.slug.es-ES', $slug);
        $page = $client->getEntries($query);

**Comment by mddanishyusuf** [comment]
@rogervila but there is no slug filed in JSON data when we get all entries. I need specific entries by a slug.
