### ISSUE TITLE
setInclude not working

### ISSUE THREAD

**Issue by dstuessy** [contentful/contentful.php#165]
Hi, 

I was just trying to query our account using this PHP API wrapper. Querying by content_type seems to work fine, but for some reason fails with entry links. Below is a snippet of my usage:

``` php
        $query = (new Query())
            ->setContentType('topic')
            ->where('fields.title', $request->getAttribute('title'))
            ->setInclude(2);
        $videos = $client->getEntries($query);
```

The include option works fine if I build the request myself and fetch the data using cURL. 

Any ideas what's wrong? Not sure if I'm just not using the wrapper correctly.

Thanks!

**Comment by dborsatto** [comment]
Hey @dstuessy 🙂
Can you provide some more info, so we can try to understand your problem? I'm interested in what the expected result is compared to the actual result, and the different behavior you experience when using setInclude.

Contentful's API uses include=1 when no explicit parameter is defined, and the SDK should resolve links automatically, at the cost of an extra query, so using setInclude or not should yield the same result, with the underlying difference of having done more queries behind the scenes. Let me know your answers to my question above, so we can start debugging your issue 👍

**Comment by dstuessy** [comment]
Hi @dborsatto 

Hm... maybe it's just a matter of me misreading the docs. haha

Here is what I expected to get:
``` json
{
    "sys": {
        "type": "Array"
    },
    "total": 1,
    "skip": 0,
    "limit": 100,
    "items": [
        {
            "sys": {},
            "fields": {
                "title": "Cars",
                "content": [
                    {
                        "sys": {
                            "type": "Link",
                            "linkType": "Entry",
                            "id": "_id"
                        }
                    },
                    {
                        "sys": {
                            "type": "Link",
                            "linkType": "Entry",
                            "id": "_id"
                        }
                    }
                ]
            }
        }
    ],
    "includes": {
        "Entry": [ {}, {} ]
    }
}
```

but actually got this:

``` json
{
    "sys": {
        "type": "Array"
    },
    "total": 1,
    "skip": 0,
    "limit": 100,
    "items": [
        {
            "sys": {},
            "fields": {
                "title": "Cars",
                "content": [
                    {
                        "sys": {
                            "type": "Link",
                            "linkType": "Entry",
                            "id": "_id"
                        }
                    },
                    {
                        "sys": {
                            "type": "Link",
                            "linkType": "Entry",
                            "id": "_id"
                        }
                    }
                ]
            }
        }
    ]
}
```

Using `https://cdn.contentful.com/spaces/{my_space}/entries?access_token={my_token}&content_type={type}&fields.title=Cars&include=2` with a cURL request, seems to give me the former, though.

**Comment by dborsatto** [comment]
That looks weird indeed.
What do you say about opening a support ticket on contentul.com? So I can better take a look at your issue and see what we can find out 🙂

**Comment by dstuessy** [comment]
Hi @dborsatto :)

Sorry for the extremely late reply. I'll open a support ticket with this github issue as a reference!

**Comment by dborsatto** [comment]
Hey @M-Porter,

Daniel created a support ticket, but then he never replied with some info I asked, so the ticket was archived.

For this case, are you having a similar issue? To be honest I can't fully understand the initial problem because the examples were about JSON, whereas the SDK should work as an abstraction thus making the underlying JSON irrelevant. Do you have any input on the topic?

Cheers,

Davide

**Comment by dborsatto** [comment]
Hey,

I'm closing this (again). If you have any more questions, don't hesitate to reach out.

Davide

**Comment by officialbalazs** [comment]
The returned `ResourceArray` does not seem to include the "includes" array that both the API and the Javascript API return.

**Comment by dborsatto** [comment]
@officialbalazs The SDK handles the `includes` array internally and does not directly expose it. When you try to access those resources (through the original entry) the SDK will know that they've already been preloaded, and will not make further requests.

**Comment by dborsatto** [comment]
You can not access it, but as I said, there will be no extra API requests.

If the `includes` array contains an entry/asset, the SDK will _not_ make extra requests when trying to fetch it (both when accessing it from another entry with something like `$blogPost->getImage()` or when calling `$client->getAsset($assetThatWasAlreadyFetchedId)`), because it will keep a copy of the resource in memory and use it instead of calling the API.

You can call `$client->getMessages()` for accessing a list of the API requests that have been made (it returns a list of `Contentful\Core\Api\Message` objects), and see for yourself that there shouldn't be extra API calls.
