### ISSUE TITLE
Call to undefined (magic) method

### ISSUE THREAD

**Issue by willjrobinson** [contentful/contentful.php#17]
Hi,

We have a field in Contentful with the id 'echoId'. When we call '$entry->getEchoId()' we get a "Call to undefined method Contentful\\Delivery\\DynamicEntry::getEchoId()"

You can see this error here: http://staging.api.bmlabs.org/api/entry/1115

Why would this one magic method/field name cause an error?

We tested against: echo, testId, and other fields, and we've not come across this issue anywhere else.

Thanks,

Will

**Comment by Khaledgarbaya** [comment]
Hi @willjrobinson ,
isn't [this](https://github.com/contentful/contentful.php/issues/9) the same issue you are having ?

**Comment by graymic** [comment]
@Khaledgarbaya you can easily replicate this, by creating a field called 'Echo ID'. If you try invoking getEchoId() the __call Magic Method will try and return the property echoId. Which oddly enough does exist but cannot be called. For example, if you were to invoke ->getContentType()->getFields() on the DynamicEntry, you will see the 'echoId' field does in fact exist as a field type.

**Comment by willjrobinson** [comment]
Yeah @Khaledgarbaya it is. We did some tests and thought we were only seeing it with this one field (not other ...Id fields)...

Cheers!
