### ISSUE TITLE
Mock Client Call

### ISSUE THREAD

**Issue by tucq88** [contentful/contentful.php#170]
In order to write independent test, I want to mock Delivery/Client and then fake the return without actually hit Contentful. But I don't see any way to do it. 

Could you please give me a suggestion?

**Comment by dborsatto** [comment]
Hey @tucq88, thanks for reaching out!

Internally the SDK is using for this kind of testing a library called [PHP-VCR](https://github.com/php-vcr/php-vcr), which lets you record the interactions and save them, so the next time they will be recorded and you won't hit the API. We also set up a listener in the `phpunit.xml.dist` so we can use another library in the PHP-VCR family, which lets us use annotations to use different recordings on every test. If you don't want to ever hit the API, you can manually construct the JSON objects so you effectively treat them as mocks.

Take a look:

- [composer.json](https://github.com/contentful/contentful.php/blob/master/composer.json)
- [phpunit.xml.dist](https://github.com/contentful/contentful.php/blob/master/phpunit.xml.dist)
- [bootstrap.php](https://github.com/contentful/contentful.php/blob/master/tests/bootstrap.php)
- [test files in `tests/E2E`](https://github.com/contentful/contentful.php/tree/master/tests/E2E)
- [test recordings in `tests/recordings`](https://github.com/contentful/contentful.php/tree/master/tests/recordings)

Let me know if this helps!

Davide

**Comment by tucq88** [comment]
Thanks @dborsatto , I'm checking it out. Much appreciated 👍

**Comment by dborsatto** [comment]
You're welcome 🙂 
I'm closing the issue, if you have any more questions feel free to reach out again 👍
