### ISSUE TITLE
Serialization of exception which contains closures in stacktrace cause problems

### ISSUE THREAD

**Issue by bestit-tkellner** [contentful/contentful.php#174]
The serialize function of src/Log/LogEntry.php file cause problems if the exception contains closures in stack trace because it's not possible to serialize this.

**Comment by dborsatto** [comment]
I'll try to reproduce the bug, but your description makes complete sense.
The problem is, I'm not completely sure how to work around this. I'll need to investigate a bit 🤔

**Comment by bestit-tkellner** [comment]
I've created a pr with a fix for this problem. I use the traceAsString function of the exception class to prevent this problem.
