### ISSUE TITLE
Release date of 0.7.x?

### ISSUE THREAD

**Issue by graymic** [contentful/contentful.php#18]
Hey guys, 

RE this ticket - - when is 0.7.x going to be released so that we can have a workable solution surrounding fields that may have "*Id*" in their field names?

https://github.com/contentful/contentful.php/issues/9

Thanks,

Michael

**Comment by realityking** [comment]
Hey Michael,

I've just tagged [0.6.5-beta](https://github.com/contentful/contentful.php/releases/tag/0.6.5-beta) that includes that fix. Sorry for the delay.

Cheers,
Rouven
