### ISSUE TITLE
How can I check for a resource not found error?

### ISSUE THREAD

**Issue by flrrrhoffpauir** [contentful/contentful.php#180]
Not really an issue, but how can I catch various errors? Specifically `Resource Not Found`

Is there a forum or better place for these types of questions? Thanks

**Comment by dborsatto** [comment]
Hey @flrrrhoffpauir,

please check out [Contentful Community](https://www.contentfulcommunity.com/), it's a forum-like website where users can get in touch with us with "generic" questions (ie, stuff that doesn't directly involve private data, for which opening a ticket would be a better solution). We also have a [public Slack](https://www.contentful.com/slack/) where users can post questions. I think either one of those will be fine for you.

Thanks 🙂
