### ISSUE TITLE
Triggered error after requesting the value of an optional parameter.

### ISSUE THREAD

**Issue by tzfrs** [contentful/contentful.php#20]
I'm using the Contentful-Bundle but I think the problem is inside the core. 

We have some optional parameters in Contentful, like "content" or "excerpt". When we now retrieve our entries and iterate over them, we want to check if the property is defined before outputting it. So let's say we have one entry with no content, but an excerpt

```
{% for entry in content.entries %}
    <article>
    {% if entry.getExcerpt() %}
        <p>{{ entry.getExcerpt() }}</p>
    {% endif %}

    {% if entry.getContent() %}
        <h3>{{ entry.getHeadline() }}</h3>
    {% endif %}
```

The first if works without problems but the second triggers the error `trigger_error('Call to undefined method ' . __CLASS__ . '::' . $name . '()', E_USER_ERROR);` in `Contentful\Deliver\DynamicEntry` in line 135. If I replace this line with `return null` it works without problems. It seems that the API doesn't let us check for optional parameters. 

What would we need to do to make this possible?

**Comment by realityking** [comment]
Are you sure you don't have a typo anywhere? The way `DynamicEntry` works is that it fetches the content type and depending on the field existing or not you should either get `null` or the error you mentioned.

In case you can't find an example, please submit a support ticket that contains some short sample code and the space ID and auth token for your space. I'll try to reproduce the error on my machine.

**Comment by calumbrodie** [comment]
1) FYI in twig you don't need the full method name with brackets, just use {{ entry.excerpt }}
2) @realityking It would be nice to implement ArrayAccess on the DynamicEntry (as perhttps://github.com/usemarkup/contentful/blob/master/src/DynamicEntry.php) so that the entry can be treated as an array (for templating language less forgiving that twig)

**Comment by realityking** [comment]
Closing this since I haven't heard back.

@calumbrodie Your request has not been forgotten, I've opened #50 to keep track of it.

**Comment by tzfrs** [comment]
Sorry. Totally forgot about this topic. It was indeed an error on my site. I used the same twig template for two different content types without noticing it, because they are pretty similar

**Comment by realityking** [comment]
Thanks for reporting back I already figured it was something like that!
