### ISSUE TITLE
Using magic methods to get field values breaks PHP conventions

### ISSUE THREAD

**Issue by fireproofsocks** [contentful/contentful.php#200]
PHP functions and method names are case insensitive, so it is unidiomatic for the SDK classes to rely on specific capitalization when getting field values.  At worst, this can lead to fatal errors, and at best it is opaque to force the developer to guess how you might be manipulating the field name behind the scenes.

Let's assume that I am fetching entries of a content type named "my_thing" that has a field named "seo_copy".

```
$client = new \Contentful\Delivery\Client($accessToken, $spaceId);

$query = (new \Contentful\Delivery\Query())
    ->setContentType('my_thing')
    ->where('fields.slug', 'xyz');

$entries = $client->getEntries($query);

foreach ($entries as $entry) {
    print $entry->getSeo_Copy() . PHP_EOL; // fatal error
    print $entry->getSeoCopy() . PHP_EOL; // fatal error
    print $entry->getSEO_COPY() . PHP_EOL; // fatal error
    print $entry->getSeo_copy() . PHP_EOL; // this works
    print $entry->getseo_copy() . PHP_EOL; // this also works
}
```

## Expected Outcome:
I should be able to retrieve my field value no matter how I have capitalized my function name.  Calling any other PHP function or method is not case sensitive.  `print` == `PRINT` == `pRiNt` == `PRInt` etc.

## Actual Outcome:

The method name capitalization matters.  Using a variation that is not supported results in a fatal error like the following:

```
Fatal error: Call to undefined method Contentful\Delivery\DynamicEntry::getSeoCopy() in vendor/contentful/contentful/src/Delivery/DynamicEntry
```

## Recommendation:

It would be more consistent and require less vetting code in the DynamicEntry's `__call` method if the class provided a `get($field)` method that accepts the exact field identifier.  Likewise, you could wire this up to use a magic `__get()` method to retrieve object properties (and PHP variable and properties are case sensitive, so this would not have the same problem of running afoul of known PHP conventions/limitations).  Alternatively, if field IDs in Contentful are not case sensitive, then the getter functions could normalize field IDs prior to looking for values (e.g. make all field identifiers lowercase).

**Comment by fireproofsocks** [comment]
Makes sense.  camelCase is fine as a suggestion (the Contentful admin definitely pushes you towards that), but snake_case and other naming conventions must also be functional.  Either way, I fully support deprecating the `__call` method.  And to clarify, I am in no way encouraging "relying" on case insensitivity, I'm just pointing out a discrepancy that is problematic an unidiomatic.

**Comment by dborsatto** [comment]
Awesome ☺️ as I said, I'm currently already working on this, so I'll close this issue, but thanks for bringing it up, it validates my assumption that a better way of handling fields was needed!

Cheers,

Davide
