### ISSUE TITLE
How to perform full-text or field-based searching?

### ISSUE THREAD

**Issue by giles-v** [contentful/contentful.php#226]
The CF Delivery API docs [state](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/full-text-search):

> It's possible to perform a full-text search across all text and symbol fields with the `query` parameter.
> 
> You can perform a full-text search on a specific field with the `[match]` operator.

I can't see a way to take advantage of this using the PHP SDK as it exists. Is that correct? Maybe I'm not understanding how to use magic methods to support params/operators which don't have an explicit PHP method defined.

**Comment by dborsatto** [comment]
Hey @giles-v,

in PHP you can use the `query` operator with a `Contentful\Delivery\Query` object:

``` php
$query = (new Contentful\Delivery\Query())
    ->where('query', $searchString);

$entries = $client->getEntries($query);
```

The snippet is taken from the docs. I'm not sure if you saw it, but clicking on "Query entries" in the docs will open a sidebar where you can see a snippet for each of the platforms we support, including PHP.

Anyway, the method `where` of the `Query` object requires two parameters: the name of the filter to use, and its value. The name of the filter can be simply the name of a field (for instance `fields.title`, `fields.body`, `fields.updatedAt`) or in this case an actual string with the value `'query'`. The second parameter will then be used as the value of that filtering operation. Overall, I suggest you take a look at the snippets in the docs, the should cover all possible situations.

If you still need help, feel free to keep commenting here 🙂

**Comment by giles-v** [comment]
Thank you for this!
