### ISSUE TITLE
Content Management API

### ISSUE THREAD

**Issue by rogervila** [contentful/contentful.php#26]
I've seen that this repository only supports Content Delivery API.
Are there plans for introducing Content Management API and Content Preview API?

If you want I can help to implement them.

Thank you.

**Comment by gholias** [comment]
Im also trying to create a PHP SDK for the Content Management. 
@rogervila Maybe we could talk?

**Comment by wawrzynkiewicz** [comment]
i'm interested in write access SDK too, @gholias can you contact me. regards

**Comment by realityking** [comment]
Hey everyone and especially @rogervila, @gholias and @wawrzynkiewicz. We've been mum on a PHP CMA SDK for a long time but now I can reveal that we're actively working on one.

We'll be opening a private alpha release later this week and then slowly expand access. If you're interested in joining the private alpha please send me an email at rouven@contentful.com and I'll get you on the list.

**Comment by realityking** [comment]
I'm happy to announce that we just open sourced the upcoming CMA SDK. You can find it here: https://github.com/contentful/contentful-management.php

It's still work in progress. Please do test it and give feedback :)
