### ISSUE TITLE
\Contentful\Delivery\Client->getSpace() doesn't take enviromentId into account.

### ISSUE THREAD

**Issue by kiliansch** [contentful/contentful.php#260]
This leads to a fail when using an API Key which is not allowed for the master enviroment.

**Comment by dborsatto** [comment]
Hey there,
the getSpace() method calls an endpoint which is not environment-aware, so it's probably the API itself which should handle this differently. Right now I can't work on this, but I'll pass this on to our other teams 🙂

**Comment by dborsatto** [comment]
@kiliansch this should be solved in version [4.1.1](https://github.com/contentful/contentful.php/releases/tag/4.1.1)
