### ISSUE TITLE
Wrong documentation php where field exist

### ISSUE THREAD

**Issue by minimit** [contentful/contentful.php#266]
https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/existence/query-entries/console/php

In the doc the php documentation have a wrong code`->where('fields.tags', ['flowers', 'accessories'], 'exists');` should be `->where('fields.tags[exists]', true);`

**Comment by Enviii** [comment]
Same issue on the inclusion: 

Docs should be re-written to say the following because that's what actually works. The 3rd parameter in the documentation does not actually work. 
`->where('fields.slug[in]', ['doc1', 'doc2', 'doc3']);`

**Comment by pgrigoruta** [comment]
Documentation has been updated, thanks for finding this!
