### ISSUE TITLE
Cannot fetch large number of independent entries

### ISSUE THREAD

**Issue by e1himself** [contentful/contentful.php#277]
Release v4.1.2 includes protection against an infinite loop of entry referencing itself.

But I believe the protection code has introduced a regression that prevents fetching multiple independent entries one-by-one.

See: https://github.com/contentful/contentful.php/commit/e29d218f8eb5bee69168d3cefc3e72d7a38dacd4#r36980490

https://github.com/contentful/contentful.php/blob/e29d218f8eb5bee69168d3cefc3e72d7a38dacd4/src/Client.php#L343-L353

Here the `$currentDepth` property increments before `->requestWithCache()`, but never decrements. It only resets back to 1 when *getEntry()* is invoked `(MAX_DEPTH + 1)` times. But it doesn't mean that `(MAX_DEPTH + 1)` call was caused by a loop. It may also be another entry being fetched.

**Comment by e1himself** [comment]
Meanwhile, we've downgraded to 4.1.0 to fix the problem here.

**Comment by pgrigoruta** [comment]
@e1himself , thanks for bringing this up, we have just released 4.1.3 which fixes this issue.
