### ISSUE TITLE
Flaws in self-referenced entries handling fix

### ISSUE THREAD

**Issue by e1himself** [contentful/contentful.php#280]
@pgrigoruta 

Releases 4.1.12, 4.1.13 and 4.1.14 are related to fixing fetching of self-referenced entries.

However, I still see some problems with this code that can lead to `currentDepth` value being improperly updated.

Consider these two cases:

1. An entity referencing itself

   - `getEntry('foo')` is called 1st time -- `currentDepth` is 1, gets incremented to 2
   - `getEntry('foo')` is called 2nd time -- `currentDepth` is 2, gets incremented to 3
   - ...
   - `getEntry('foo')` is called 20th time -- `currentDepth` is 20, but resets to 1 
   - we go one level up the stack, `currentDepth` goes from 1 to 0
   - we go 2nd level up the stack, `currentDepth` goes from 0 to -1
   - ...
   - we go 20th level up the stack, `currentDepth` goes from -18 to -19
   
   When the call is finished `currentDepth` is set to `-19`. Every next request to a self-referencing entry will increase the depth limit by 20, resulting in higher API consumption and higher monthly bills.

2. If an exception is thrown during fetching an entry, and then the outer code recovers from it, the `currentDepth` property will not be reverted back.

   - `getEntry('foo')` is called 1st time -- `currentDepth` is 1, gets incremented to 2
   - `getEntry('bar')` is called 2nd time -- `currentDepth` is 2, gets incremented to 3
   - `getEntry('baz')` is called 3rd time -- `currentDepth` is 3, gets incremented to 4
   - ...
   - `getEntry('baz')` is called 9th time -- `currentDepth` is 9, gets incremented to 10
   - a `ServerException` is thrown, we exit all stack levels, leaving `currentDepth` set to 10
   
---------------

That being said, I suggest changing the code to this:

```php
if ($this->currentDepth > self::MAX_DEPTH) {
    /** @var Entry $entry */
    $entry = $this->resourcePool->get('Entry', $entryId, ['locale' => $locale]);
} else {
    ++$this->currentDepth;
    try {
        /** @var Entry $entry */
        $entry = $this->requestWithCache(
            '/spaces/' . $this->spaceId . '/environments/' . $this->environmentId . '/entries/' . $entryId,
            ['locale' => $locale],
            'Entry',
            $entryId,
            $this->getLocaleForCacheKey($locale)
        );
    } finally {
        --$this->currentDepth;
    }
}
```

**Comment by pgrigoruta** [comment]
Thanks again for all the feedback, this change was merged in the latest release.

**Comment by e1himself** [comment]
Thanks Paul :+1:
