### ISSUE TITLE
v5.0 release is not switched to contentful/rich-text.php v2.0

### ISSUE THREAD

**Issue by e1himself** [contentful/contentful.php#281]
@pgrigoruta 

The 5.0 release created yesterday mentions breaking changes in the `rich-text` dependency. 
But `composer.json` was not updated. The release is still using `contentful/rich-text.php` of `~1.2`.

### Fix

`composer.json` should be updated to require `contentful/rich-text.php: ~2.0`

**Comment by pgrigoruta** [comment]
Fixed, thanks for noticing
