### ISSUE TITLE
How to post content to entry using php

### ISSUE THREAD

**Issue by thanhansoft** [contentful/contentful.php#287]
Hi admin,
I'm using contentful.php. I can get ID contentType.
How to submit content to entry.
Please help me

**Comment by pgrigoruta** [comment]
Hello @thanhansoft , the Contentful Management librarry can be used for creating/updating posts - https://github.com/contentful/contentful-management.php . Here is a link to a code example on how to add an entry - https://github.com/contentful/contentful-management.php#entries-and-entry-snapshots .
