### ISSUE TITLE
Include with all() doesn't work with nested links

### ISSUE THREAD

**Issue by eerohakio** [contentful/contentful.php#291]
SDK Version: 6.0.1
PHP Version: 7.2.28

**Description**
- Currently method `Entry::all()` only resolves first level of links.

**Preconditions:**
- ContentType A has reference field that includes reference to ContentType B
- ContentType B has reference field that includes reference to ContentType C

Only ContentType B links are resolved from ContentType->all()
This causes issue where backend(PHP) data should be consumed as json and links are not resolved similarly to Contentful JS SDK.

In attached picture theres field called `content` which is reference field to other content types. As seen only first level of content is resolved and second level only includes Contentful\Core\Api\Link.

![Screenshot 2020-05-20 at 11 21 10](https://user-images.githubusercontent.com/31061105/82423756-e7022d80-9a8c-11ea-80c8-6588c286c729.png)

Code for getting $entry in attached picture:
```        
$query = new Query();
$query->setInclude(10);
$query->setLocale('en-US');
$query->setContentType('page')
      ->where('fields.slug', $slug);
$contentfulClient->getEntries($query);
$entry = [
    'fields' => $entry->all(),
    'sys'    => $entry->getSystemProperties()
];
```

Overcomed the issue by looping through fields and if they are reference fields then calling ->all() for all of them but this is not best solution as the client should handle it.

**Comment by alex-osborn** [comment]
I'm running into a similar problem.

SDK Version: 6.0.3
PHP Version: 7.4.5

![Screen Shot 2020-05-25 at 9 27 40 PM](https://user-images.githubusercontent.com/880420/82800163-53d35880-9ecf-11ea-883a-5a79541a373a.png)

In my case, the links aren't even being returned as `Link` objects but plain arrays, see "categories" in the screenshot.

**Comment by pgrigoruta** [comment]
The longer explanation is given at https://github.com/contentful/contentful.php/issues/256#issuecomment-438957073 

Basically doing:
```
$entry->getReference()->getReference()->getTitle()
```
Will work, but var_dump wont since data is serialized.

**Comment by baj84** [comment]
Hi @pgrigoruta Could you please expand on your answer for how we can simply get an entry and it's nested assets?

Do we need to loop through each entry and on each field call `$entry->getReference()->getReference()->getTitle()`?

**Comment by baj84** [comment]
Hi @eerohakio Are you please able to share your full solution?
