### ISSUE TITLE
Potential segfault?

### ISSUE THREAD

**Issue by Daronspence** [contentful/contentful.php#293]
We're still debugging this but curious if you have had any reports of segfaults the library?

We're running a custom WordPress plugin on a popular host (WP Engine) that uses the SDK and it somewhat reliably will cause a segfault when the SDK is used in any way.

I know there's a lot of other potential other code that could be interfering but just thought I would check if there were any reports?

As a work around, do you know how we could rewrite a small portion of the SDK to perform a couple of queries and resolve the links? We can make the REST calls ourself, but the recursion needed to process the entries is confusing!

Cheers

**Comment by Daronspence** [comment]
Update in case any one else happens to stumble across this one day. Instead of rewriting to use the Contentful REST API, we're going to use the GraphQL API instead. That solves the recursion "problem" in that it wont be necessary.

We're still not sure what caused the segfault, only that it occurs when we have the our the plugin enabled. The plugin's sole job was to make a couple of queries using the PHP SDK and then we would run a handful of methods on those returned objects.

Interestingly, we were trying to experiment with where _exactly_ the fault was occurring and noticed it still happened even when the only thing we instantiated was the `\Contentful\Delivery\Client`. Is there anything in that class that your team can think of that could potentially cause something like a segfault? 

WP Engine is notorious for having "tuned" their platform in a way to increase performance, so I wouldn't be surprised if their configuration messes with things like caching objects, regardless if they follow PSR specs or not.

Cheers

**Comment by Daronspence** [comment]
Final update likely for a while here. Potential reproduction steps for anyone who may want try this out.

- Create a blank WP plugin and install the Contentful PHP SDK via Composer
- Include the autoload file and then add a hook to the `plugins_loaded` action.
- Inside your callback function, instantiate the main `Client()` class used for making requests
- Hammer your server a few hundreds times relatively quickly
- Watch for segfaults

This was essentially the setup we were using on WP Engine. Not sure really what exactly in the package it could be.

Having a little more breathing room now to look at it, I wonder if the `withLowMemoryResourcePool()` would be a potential factor here. We definitely weren't handling enough requests for it to matter in terms of running out of memory, but I wonder if the extended cache pool setup was something that is unreliable on WPE servers.

It's all very strange and I would love to test it more but I personally don't have the extra resources or time to do that now.

Curious if anyone else has any thoughts, because I'm stumped ¯\_(ツ)_/¯ 

Cheers

**Comment by pgrigoruta** [comment]
Hi @Daronspence , there were a few issues in the past, mostly around self-referencing entries that caused out of memory/too much recursion, here are a couple - https://github.com/contentful/contentful.php/issues/278 , https://github.com/contentful/contentful.php/issues/105 . I guess they could cause segfaults. 

However, the issues were fixed and verified a while ago, first can you make sure you are on the latest version? If that's true, try getting more information from WP Engine, I would expect an error behind the segfault - was it out of memory? If not, what error did it crash with?

We need a bit more information as I am not aware of any issues specific to WPEngine, or any issues that could cause segfaults under certain conditions.

**Comment by Daronspence** [comment]
Thanks @pgrigoruta for linking those. We were on the latest version, unfortunately. 

Also unfortunate, WPE wasn't able to get a solid request on their end with all of the debugging tools running. We had it up for almost a full day and they weren't able to capture any of the 502 requests we were generating, but they could see in some log that it was indeed a segfault.

I knew you probably didn't have a secret patch up your sleeve, but it never hurts to ask :) 

Eventually we'll get this in front of them again and have them debug it more.

Cheers

**Comment by pgrigoruta** [comment]
Thanks @Daronspence , I will close this for now as we don't have enough data to move forward, feel free to re-open if you find out more.
