### ISSUE TITLE
BaseClient::messages memory exhaustion

### ISSUE THREAD

**Issue by brettmc** [contentful/contentful.php#294]
I am using the SDK (v6.0.3) in a long-running CLI process, to periodically query contentful and process the response.

In tracking down what we originally thought was a memory leak, whereby our PHP process would eventually exhaust memory and die, I found that in fact the culprit was `Api\BaseClient::messages` storing all of the http requests and responses in an ever-growing collection (which can grow really fast if you're pulling down non-trivial amounts of data).

I can think of a couple of ways this could be avoided:
* provide a `ClientOptions::withoutMessageLogging()` method which controls whether messages are stored (maintaining the storing of messages as the default behaviour)
* adding an `Api\BaseClient::clearMessages()` method to allow clearing out on-demand

I'd be happy to submit a PR if I can get some guidance as to whether either of these options seem reasonable?

**Comment by pgrigoruta** [comment]
Hi @brettmc , thanks for finding this! I think both approaches are good and serve different use cases, so best is to implement them both. If you have a PR (full or partial), please submit it and we can finish the implementation/add test coverage if needed.

**Comment by brettmc** [comment]
step 1, I have submitted a PR against contentful-core.php (https://github.com/contentful/contentful-core.php/pull/43)
If that's all cool, then there will be a small follow-on patch in this repo

**Comment by pgrigoruta** [comment]
Thanks @brettmc , I just merged this branch
