### ISSUE TITLE
Undefined function curl_reset() on GuzzleHttp

### ISSUE THREAD

**Issue by raenk** [contentful/contentful.php#3]
When trying $client->getEntries();

I'm getting this error:
Call to undefined function GuzzleHttp\Handler\curl_reset() in ../guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 78

Reinstalled all libraries related to contenful to no avail.

Thanks

**Comment by realityking** [comment]
Hi raenk,

What PHP version are you using? The SDK requires at least PHP 5.5.9, from the error message it looks like you're using some version < 5.5.

**Comment by raenk** [comment]
Hi,

5.5.32

php -v
PHP 5.5.32 (cli) (built: Feb  4 2016 23:43:24)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by realityking** [comment]
Hi raenk,

I'm a bit baffled to be honest. Could you please execute the following code in your shell and post the output? Thank you. `php --rf curl_reset` 

Did you test Contentful with a CLI script or web page? I know this is the equivalent of the "is it plugged in" question, but could you please make sure you're using the same version for Web and CLI.

**Comment by raenk** [comment]
Hi,

Your suggestion woke me up. Just realized that PHP was just updated, so an
apache restart was needed to pick it up :)

Thanks a lot!

**Comment by realityking** [comment]
Glad I could help 😀
