### ISSUE TITLE
Support for Tags

### ISSUE THREAD

**Issue by philipnewcomer** [contentful/contentful.php#300]
Hi, I'm not seeing any way to get an entry's tags using this package. I know the tags are present in the API response, but don't appear to be supported by the SDK. Am I missing something, or are tags not yet supported by the package? Is this something that's planned?

**Comment by Kyoss79** [comment]
I second this. I am not able to find the tags anywhere in the PHP SDK.

**Comment by Sebb767** [comment]
Hi @philipnewcomer @Kyoss79 ,

Tag support for management and delivery SDKs is in the works and should drop soon :) I'll ping you once it's released.
