### ISSUE TITLE
Filtering not working on preview API

### ISSUE THREAD

**Issue by bmerigan** [contentful/contentful.php#303]
By design the Preview API picks up incomplete draft content so I wanted to find a way to stop it returning incomplete entries i.e., where some fields are not filled in.  

I used the below code example:
```
$query = (new Query())  
            ->setContentType(units)  
            ->where('fields.title[exists]', true)  
            ->where('fields.unitDetails[exists]', true)  
            ->where('fields.unitDetails.sys.contentType.sys.id[match]', 'unitDetailsData')  
            ->where('fields.unitDetails.fields.unitName[exists]', true)  
            ->where('fields.unitDetails.fields.unitUrl[exists]', true)  
```
And even though none of the unitDetails fields were filled in, an incomplete entry was still returned:
```
"fields": {  
                "title": "My best unit"  
            }  
}
```
Documentation reference: [https://www.contentful.com/developers/docs/references/content-preview-api/#/reference/search-parameters/existence](https://www.contentful.com/developers/docs/references/content-preview-api/#/reference/search-parameters/existence)

**Comment by Sebb767** [comment]
Hi Ben,

I've managed to reproduce this locally. It's a bit unintuitive, but you actually need to set the query parameter value to `'true'` (a string) instead of `true` (a boolean). So this should work:

```
$query = (new Query())  
            ->setContentType(units)  
            ->where('fields.title[exists]', 'true')  
            ->where('fields.unitDetails[exists]', 'true')  
            ->where('fields.unitDetails.sys.contentType.sys.id[match]', 'unitDetailsData')  
            ->where('fields.unitDetails.fields.unitName[exists]', 'true')  
            ->where('fields.unitDetails.fields.unitUrl[exists]', 'true') ;
```

Hope this works for you :)

**Comment by bmerigan** [comment]
The documentation I've linked to above specifically says it is a boolean.
On your advise I tried both single-quote and double-quoted strings (`'true' "true"`), but the result was the same, the incomplete entry was still returned.

**Comment by bmerigan** [comment]
I don't know why, but I've been making changes to the models and it's started working correctly.  Will keep going and have an answer in a day or 2.

**Comment by bmerigan** [comment]
Sebb above is correct in regards to the PHP Contentful library.
At the command-line, and via Postman using `true` works as intended.  But when using the PHP library `true` gets mangled.  To get filtering to work with the PHP library you must use `'true'`
