### ISSUE TITLE
Version 6.2.0 contains BC breaks

### ISSUE THREAD

**Issue by mmenozzi** [contentful/contentful.php#305]
Version 6.2.0 of this package contains backward incompatible changes from 6.1.0: https://github.com/contentful/contentful.php/compare/6.1.0...6.2.0

You added methods to an interface (ClientInterface) which is a BC break.

You should follow [Semantic Versioning](https://semver.org/).

**Comment by Sebb767** [comment]
Hi @mmenozzi ,

this is indeed a bc break - thanks for bringing that to our attention. We're trying to follow SemVer; this break was not intentional and we're working on a fix for this right now.

Sorry for the inconvenience!

**Comment by mmenozzi** [comment]
No problem!
I suggest you to integrate https://github.com/Roave/BackwardCompatibilityCheck in your CI to avoid this in the future.

**Comment by Sebb767** [comment]
Hi @mmenozzi ,

we investigated this and, unfortunately, rolling back the change would likely break more code (that is already using the new versions) than saving code that doesn't. I'll instead add a warning to the README.

Additionally, adding the checker you suggested seems like a good option - hopefully it prevents such incidents in the future. Thanks again for bringing this to our attention :)

**Comment by mmenozzi** [comment]
You're welcome @Sebb767! Thank you for your attention to the this.

**Comment by Sebb767** [comment]
The check is now in the composer.json and will be integrated into the CI pipeline in the next release :)

**Comment by mmenozzi** [comment]
Great @Sebb767!
