### ISSUE TITLE
Library not compatible with Google Auth because of not supporting PSR Cache in version 2

### ISSUE THREAD

**Issue by wlasnapl** [contentful/contentful.php#308]
Can this library support also psr/cache in version 2 (not only 1 and 3)? Now I'can't upgrade to Symfony 6 project using Google Auth (https://github.com/googleapis/google-auth-library-php) because they require version 2 and here is required 3 (in 6.3.0).

**Comment by Sebb767** [comment]
Hi,

last time, adding v2 broke some dependencies, that's why only v3 was added. I'll look into whether this is fixable :)

**Comment by kwivix** [comment]
Hi,

I've fixed this in the following PR's:

- https://github.com/contentful/contentful-core.php/pull/53
- https://github.com/contentful/contentful.php/pull/309
- https://github.com/contentful/ContentfulBundle/pull/54

**Comment by Sebb767** [comment]
Should be resolved with the just released 6.4.0 :)
