### ISSUE TITLE
Deprecation warnings in PHP 8.1

### ISSUE THREAD

**Issue by dbebawy-modus** [contentful/contentful.php#315]
1.   1x: Return type of Contentful\Delivery\SystemProperties\BaseSystemProperties::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
2.   1x: Return type of Contentful\Delivery\Resource\Entry::offsetExists($name) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
3.   1x: Return type of Contentful\Delivery\Resource\Entry::offsetGet($name) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
4.   1x: Return type of Contentful\Delivery\Resource\Entry::offsetSet($name, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
5.   1x: Return type of Contentful\Delivery\Resource\Entry::offsetUnset($name) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

**Comment by Sebb767** [comment]
Hey @dbebawy-modus ,

unfortunately, we can't add this attributes or the return type until we deprecate support of PHP7, which we can't do until at least extended support for it runs out. So there's no way to get rid of these warning for now.

**Comment by dbebawy-modus** [comment]
The composer.json file only supports `"php": "^7.2|^8.0",`.
Support for PHP return types was added in PHP 7.0 and the `void` type was added in PHP 7.1.

For the first 3 items, we can resolve the notices by adding the appropriate return types (mixed, bool).
```
@@ -126,7 +126,7 @@ class Entry extends LocalizedResource implements EntryInterface, \ArrayAccess
     /**
      * {@inheritdoc}
      */
-    public function offsetGet($name)
+    public function offsetGet($name): mixed
     {
         return $this->get($name);
     }
@@ -134,7 +134,7 @@ class Entry extends LocalizedResource implements EntryInterface, \ArrayAccess
     /**
      * {@inheritdoc}
      */
-    public function offsetExists($name)
+    public function offsetExists($name): bool
     {
         return $this->has($name);
     }
@@ -50,7 +50,7 @@ abstract class BaseSystemProperties implements SystemPropertiesInterface
     /**
      * {@inheritdoc}
      */
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         return [
             'id' => $this->id,

```

The last 2 items can be resolved by adding the `void` return type. This is supported in PHP >= 7.1.
```
@@ -142,7 +142,7 @@ class Entry extends LocalizedResource implements EntryInterface, \ArrayAccess
     /**
      * {@inheritdoc}
      */
-    public function offsetSet($name, $value)
+    public function offsetSet($name, $value): void
     {
         throw new \LogicException('Entry class does not support setting fields.');
     }
@@ -150,7 +150,7 @@ class Entry extends LocalizedResource implements EntryInterface, \ArrayAccess
     /**
      * {@inheritdoc}
      */
-    public function offsetUnset($name)
+    public function offsetUnset($name): void
     {
         throw new \LogicException('Entry class does not support unsetting fields.');
     }
```

**Comment by dbebawy-modus** [comment]
Create PR for your review/approval. https://github.com/contentful/contentful.php/pull/317

**Comment by Sebb767** [comment]
Unfortunately, the mixed return type is only available starting with PHP 8: https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.mixed .

Using bool and void is possible, though.

**Comment by Seppo-Konttinen-Solteq** [comment]
Hi @Sebb767 

Is there anything that can be done with this? We are currently doing upgrade and are blocked with this. Current Magento version EOL is 28th of Nov so se cannot wait much more longer to be able to do upgrade and testing in time.

Thanks.

**Comment by NeilMasters** [comment]
> The composer.json file only supports "php": "^7.2|^8.0",.

Is there expected full support for php 8.1 coming anytime soon?

**Comment by svenluijten** [comment]
> unfortunately, we can't add this attributes or the return type until we deprecate support of PHP7, which we can't do until at least extended support for it runs out. So there's no way to get rid of these warning for now.

This isn't true. Attributes start with a `#` which also happens to be a comment. So any attributes you add to your code will simply be ignored pre-8.1. And even if it did, that's what versioning is for. Composer will just resolve the version you need based on your environment. Tagging the next release with PHP 8.1 will not cause _any_ issues for people (STILL!) running PHP 7.x.

**Comment by Seppo-Konttinen-Solteq** [comment]
Can this be now released as the PHP7 support should be dropped?

**Comment by Sebb767** [comment]
@Seppo-Konttinen-Solteq There's unfortunately still a blocker in releasing the updated version for `rich-text`. As soon as this is resolved, I'll immediately publish a new version.

**Comment by Seppo-Konttinen-Solteq** [comment]
Thanks for the info @Sebb767 ! :)

**Comment by frankmckechnie** [comment]
Awesome work @Sebb767

**Comment by NeilMasters** [comment]
Legend.
