### ISSUE TITLE
Soft Line Returns Not Rendered to HTML

### ISSUE THREAD

**Issue by bluhring** [contentful/contentful.php#319]
In the WYSIWYG editor in Contentful, if you press <ENTER> it will create a new paragraph with extra spacing (margin) between paragraphs. But like most WYSIWYG tools, you can also press <SHIFT+ENTER> to do a soft line return where it essentially uses an HTML break tag instead of starting a new paragraph.

When I use the Contentful PHP SDK, the soft returns are not rendered, so the content on the page  has the words running together inline as opposed to starting a new line (HTML break tag). When I return to the Contentful content manager screens the WYSIWYG still shows the soft line return, so the data is there and saved, it just isn't being rendered out by the PHP SDK renderer.

$renderer = new \Contentful\RichText\Renderer();
echo $renderer->render($content->get('body'));

**Comment by Sebb767** [comment]
Those new lines are actually rendered correctly, they're just not displayed in html by default. You have three options here:

1. Use CSS to show them:

```css
.your-text-field p {
  white-space: pre-wrap;
}
```

2. Manually add breaks:

```php
echo str_replace("\n", "<br>\n", $renderer->render($content->get('body')));
```

3. Overwrite the Paragraph renderer to do the replacing:

```php
// Define this class somewhere
class CustomParagraph extends \Contentful\RichText\NodeRenderer\Paragraph
{
    /**
     * {@inheritdoc}
     */
    public function render(RendererInterface $renderer, NodeInterface $node, array $context = []): string
    {
        return str_replace("\n", "<br>", parent::render($renderer, $node, $context);
    }
}

// then, before calling render, do the following:
$renderer->pushNodeRenderer(new CustomParagraph());
```

Hope this helps!

**Comment by bluhring** [comment]
Thanks for this! The #2 "manually add breaks" seems to work fine for my needs.

**Comment by Sebb767** [comment]
Glad I could help!
