### ISSUE TITLE
Client::getEntries() cache does not work properly with different locales

### ISSUE THREAD

**Issue by fabianaromagnoli** [contentful/contentful.php#320]
If you call `Client::getEntries()` method passing a `Query` that has no locale set, the cache key will not include the locale code, so that if you have entries in different locales, you will get the same cache content for any locale.
I think it is common to build a `Query` without setting a specific locale, because in this case the `Client` uses the default locale, and in most cases that's exactly what you want.

**Comment by fabianaromagnoli** [comment]
I'm already working on a PR to fix this. Coming soon.

**Comment by Sebb767** [comment]
Fixed with [v7.0.1](https://github.com/contentful/contentful.php/releases/tag/7.0.1) - thanks!
