### ISSUE TITLE
psr/log require mismatch with Magento 2.4.4-p2

### ISSUE THREAD

**Issue by Seppo-Konttinen-Solteq** [contentful/contentful.php#322]
Hi.

When trying to take Contentful module version 7.0.0 in to use I ended up to have problem to update psr/log to version 2 or 3 as magento/ece-tools has require for version 1 ("psr/log": "^1.0")

`Problem 1
    - Root composer.json requires contentful/contentful 7.0.0 -> satisfiable by contentful/contentful[v7.0.0].
    - contentful/contentful v7.0.0 requires psr/log ^2.0|^3.0 -> found psr/log[2.0.0, 3.0.0] but these were not loaded, likely because it conflicts with another require.`

Should I start poking Adobe for this or is there change to have Contentful module to support psl/log version 1?

**Comment by Sebb767** [comment]
There originally was an incompatibility with PHP v7. However, as the library doesn't support PHP7 in v7 anymore, we can actually add back support for psr/log v1. I'll do so in the next patch release :)

**Comment by Seppo-Konttinen-Solteq** [comment]
Thank you @Sebb767 .

Can you tag me to the PR when it gets merged?

I actually asked about this from Magento support also and they did not have roadmap for removeing psr v1 from ECE-tools module and support v2 and v3.

**Comment by Sebb767** [comment]
@Seppo-Konttinen-Solteq I've re-added the support with [v7.0.1](https://github.com/contentful/contentful.php/releases/tag/7.0.1) :) From my testing, it should work now.

**Comment by Seppo-Konttinen-Solteq** [comment]
Thank you @Sebb767 . I will give it a try :)

**Comment by Seppo-Konttinen-Solteq** [comment]
Hi @Sebb767 . That worked but now Contentful management module gives this

Problem 1
    - Root composer.json requires contentful/contentful-management ^4.1 -> satisfiable by contentful/contentful-management[4.1.0].
    - contentful/contentful-management 4.1.0 requires symfony/console ^5.0|^6.0 -> found symfony/console[v5.0.0-BETA1, ..., v5.4.32, v6.0.0-BETA1, ..., v6.4.1] but these were not loaded, likely because it conflicts with another require.

Magento's own modules requires version 4 of symfony/console
