### ISSUE TITLE
Update support for php 8.2/8.3?

### ISSUE THREAD

**Issue by Cristina-JumpMath** [contentful/contentful.php#329]
When will the package be updated to support PHP versions 8.2 and 8.3?
I am updating the versions of my project and I get the error of incompatibility with the PHP version when running the composer update command.

Thanks!!

**Comment by Sebb767** [comment]
Hi @Cristina-JumpMath ,

we're in the process of updating all PHP libraries for the new PHP versions, which will probably be done by the end of the week. That being said, this library is already fully compatible with PHP 8.2.

**Comment by Sebb767** [comment]
Version [v7.0.2](https://github.com/contentful/contentful.php/releases/tag/v7.0.2) is fully tested on PHP8.3. Feel free to open a bug in case something is missing :-)
