### ISSUE TITLE
Content Type and Space API Requests

### ISSUE THREAD

**Issue by solomonjames** [contentful/contentful.php#37]
## Problem
When I simply want a list of entries or just an entry I never need the Space or Content Type info.  Yet the API loads this data no matter what.  It seems somewhat tied to some aspects of the DynamicEntry setup but leads to unnecessary API calls compounding.

For instance, if I am to make an `entries` call to something that has a few linked content types nested, then this one API request could lead to a count of the unique content types being pulled plus the space info.

These requests are fast, typically, but they add up and seem avoidable, or could be part of the main API response if they are indeed necessary.

## Solution
No idea.

I could override the `Client::getEntries` method and return the raw response by just using the `Client::request()` instead of `Client::requestAndBuild` but then I lose the things that are helpful about the DynamicEntry class.  Things like locale help, and loading the nested objects.

From what I can tell it's not possible to build out a DynamicEntry without the Content Type and Space metadata.

So could the API actually return all this metadata (kind of like we get with the `includes` param)?
Or can we see a way to do things without forcing those calls?

Thanks for any ideas or feedback.

@realityking Pinging you, since you are visiting next week.

**Comment by sgb-io** [comment]
Hey @solomonjames, I had the same problem as you - https://github.com/contentful/contentful.php/issues/34

There are some planned longer-term solutions but for now you can work around it using `reviveJson` (this solution worked for me - I get the space / content type meta once, cache it, then just revive it in new clients etc)
