### ISSUE TITLE
Asset get() methods can throw Uncaught Exceptions when the content model is non-localized

### ISSUE THREAD

**Issue by sgb-io** [contentful/contentful.php#38]
`Asset` methods such as `getFile()` and `getTitle()` can throw uncaught exceptions when the `Asset` in question has `localized` property set to `false`.

For example, say i have the regular `DynamicEntry` - `Car`, with a linked field `Image`, which is an `Asset`.

Let's say the `Image` looks like this:

```json
  {
    "name": "Image",
    "id": "image",
    "type": "Link",
    "linkType": "Asset",
    "validations": [],
    "localized": false,
    "required": false,
    "disabled": false,
    "omitted": false
  }
```

Now, if you attempt to `getTitle('fr')` on this `Asset` for example, the SDK will throw:

`Undefined property: stdClass::$fr`

I'd suggest the expected behaviour in this scenario should be fallback to the default value.

**Comment by graymic** [comment]
I think the approach here is definitely fall back to the default locale - if what I've read I understood. Are there any issues foreseen if we fall back to default minus the obvious?

**Comment by realityking** [comment]
I've been able to reproduce this using the following snippet:

```php
<?php
require 'vendor/autoload.php';

$client = new \Contentful\Delivery\Client('b4c0n73n7fu1', 'cfexampleapi');
$nyancat = $client->getAsset('nyancat');
var_dump($nyancat->getTitle('tlh'));
```

I'd like to clear up one misunderstanding. An asset is always localizable. Setting `localized` to false on the reference to an asset just means you can not choose different assets for different locales within the entry. The asset itself still has the title/description/file for all assets.

That said, there is a fallback logic here which is obviously not working correctly.

**Comment by tommymarshall** [comment]
Any ideas on a fix for this? I started digging in but haven't made much progress.

It's happening to us when I
*Code:*
```php
$query   = (new Query)->setContentType('article')->setLimit(10);
$entries = $this->client->getEntries($query);
```
*Error:*
```
ErrorException in ResourceBuilder.php line 156:
Undefined property: stdClass::$details
```

**Comment by tommymarshall** [comment]
So, this appears to happen when an image has not finished processing within Contentful. I found the Asset in question and it appears it was stuck in a "Processing" state (Redlined through client-specific details).

![](https://s3.amazonaws.com/vigesharing-is-vigecaring/tmarshall/16-12-30_14-10-26.png_13111065_2016-12-30_14-12-42.png)

Not 100% sure it's related to this issue; so if not let me know and I'll file a new ticket.

**Comment by realityking** [comment]
Hi @tommymarshall that's an unrelated error. The original error only occurs when actually accessing the data through a getter method. Could you please open a a support ticket and mention my name? You should not be able to publish an asset that hasn't finished processing. Thank you.
