### ISSUE TITLE
Releases without '-beta' suffix?

### ISSUE THREAD

**Issue by niels-nijens** [contentful/contentful.php#39]
According to [SemVer](http://semver.org/#spec-item-4) you're already allowed to make breaking API changes in a next 0.x release. So, the '-beta' suffix should be unnecessary.

As an added bonus you don't have to specifically add this package if you already have a Composer dependency on for instance the [ContentfulBundle](https://github.com/contentful/ContentfulBundle) for Symfony, which would improve the Developer Experience and you'd be able to better manage the dependency of the bundle on a specific version of this package.

Could you please consider this change in your release cycle?

**Comment by realityking** [comment]
It's been a long time since you opened this ticket but I wanted to let you know that we've finally released a stable version of the SDK and the ContentfulBundle. Thank you for your patience. :)
