### ISSUE TITLE
Human documentation

### ISSUE THREAD

**Issue by frankdejonge** [contentful/contentful.php#4]
There's only generated API docs, which basically says as much as my IDE does. It would be nice to have some documentation which illustrates the different use-cases of the SDK as well as the conventions around it. The project I'm currently working on uses contentful but we're hesitant to use the provided SDK because the lack hereof.

**Comment by frankdejonge** [comment]
Just saw there's docs here: https://www.contentful.com/developers/docs/php/tutorials/getting-started-with-contentful-and-php/ might be good to link to this from the repo. Common package search flows are: Packagist -> Github Repo / Readme -> Docs.

**Comment by realityking** [comment]
Hey Frank,

sorry for not responding to this earlier, I somehow missed the notification. Good catch on the docs, when we first published the SDK we didn't have any of the tutorials and later I never thought about this. I just pushed [a commit](https://github.com/contentful/contentful.php/commit/4f10171494ad0396bb6374315758a7361ab5e398) that contains links to the rest of the docs.

If there's anything missing in terms of documentation (or other things) please keep opening issues 😄 

Cheers,
Rouven
