### ISSUE TITLE
Call to a member function getFile() on null

### ISSUE THREAD

**Issue by philippkuehn** [contentful/contentful.php#5]
Hey,

I have a basic content type with title and an image:

![qsfitgc5ni](https://cloud.githubusercontent.com/assets/2500670/15273054/b47ec36a-1a8d-11e6-8043-4c66e0689517.png)

If I want to loop through all images everything is fine:

```
$assets = $client->getAssets();
foreach($assets as $asset) {
	print_r($asset->getFile()->getUrl()); // works
}
```

But if I want to loop through all entries, I don't have access to `getFile()`.

```
$entries = $client->getEntries();
foreach($entries as $entry) {
	print_r($entry->getTitle()); // works
	print_r($entry->getAvatar()); // Contentful\Delivery\Asset Object
	print_r($entry->getAvatar()->getFile()->getUrl()); // don't work: Call to a member function getFile() on null
}
```

What I'm doing wrong here?

**Comment by realityking** [comment]
Hi Philipp,

first of all sorry for the late answer. Unfortunately GitHub emails go into my private mail account, where stuff easily get lost.

My first guess would be that you have an entry that's not linked to an asset. To be sure, could you please open a ticket on https://support.contentful.com/hc/en-us and share the space ID and API key? I'll try reproducing the issue.

Cheers,
Rouven

**Comment by philippkuehn** [comment]
In the current version this is fixed for me. 👍

**Comment by realityking** [comment]
Even better 😀

**Comment by raphibolliger** [comment]
I have the same problem i can't call the `getFile()` method. But it's really strange it can resolve the value from `getUrl()` and after that the fatal error occurs. The `$frontImage` is definitely not null but the error occurs anyway.

Here my code:
```
$projectQuery = (new Query())->setContentType('project');
$projectQuery->where('include', 2);
$projects = $client->getEntries($projectQuery);

foreach ($projects as $project) {
    $title = $project->getTitle();
    $frontImage = $project->getFrontImage();
    $imageUrl = $frontImage->getTitle()->getUrl();
    print_r($imageUrl)
}
```
This produce the following output and error:
Output: //images.contentful.com/x...x/x....x/image.png
Error: **Call to a member function getTitle() on null in...**

What I'm doing wrong? Status of the Asset is Published.

@philippkuehn What was your solution? Did an update solve the problem?

**Comment by realityking** [comment]
@raphibolliger I think your error is on this line `$imageUrl = $frontImage->getTitle()->getUrl();` instead it should be `$imageUrl = $frontImage->getFile()->getUrl();`. Let me know if that works :)
