### ISSUE TITLE
Documentation: Setting language as a fallback

### ISSUE THREAD

**Issue by tommymarshall** [contentful/contentful.php#54]
## Description
I've been trying to access values of translated fields using magic methods, but am running into issues. For context, I am using the most recent version of this SDK with Laravel (though I dropped using contentful/laravel package and made my own service provider because of minimum requirements of this package).

This issue occurs whether I `setLocale` on a `new Query` or passed to `getEntry` like below.

## Code
```php
$client = new Client(..., ..., ..., null, null, 'en-US');
$entry = $client->getEntry($id, 'de');

dd($entry);
```

Spits out this content:
![](https://s3.amazonaws.com/vigesharing-is-vigecaring/tmarshall/Documentation_Setting_language_as_a_fallback__Issue_54__contentfulcontentful.php_2017-03-07_17-01-20.png)

If I take the same code and try and grab the `contentBlocks`:
```php
dd($entry->getGameAssets());
```

It gives me this:
![](https://s3.amazonaws.com/vigesharing-is-vigecaring/tmarshall/localhost3000dechampions6fGMzSBiKIC2i4woMSeWg_2017-03-03_15-28-58.png_725593_2017-03-03_18-46-52.png)

## What I Expect
`getGameAssets()` should always have access to `en-US` since it's my fallback language _and_ I do have translations for that locale

## Also occurs when using `Query`
```php
$query = (new Query)->setLocale('de');
$query->where('sys.id', $id);
$entry = $this->client->getEntries($query)[0];

dd($entry->getContentBlock());
```

**Comment by realityking** [comment]
There's definitely something wrong. Is this with 0.6.5 or with current master?

**Comment by tommymarshall** [comment]
What's currently in master.

**Comment by realityking** [comment]
Hi Tommy,

I've got a fix in #57, it'd be great if you could confirm that it resolves your issue.

The problem is not actually related to the fallback chain at all, instead it's a problem with non-localised fields. I did not check what the issue is in 0.6.5-beta. Would it be ok for you to switch to master for a while? (If so, you should pin it to a specific commit as there are a couple more breaking changes coming up)

Cheers,
Rouven

**Comment by realityking** [comment]
@tommymarshall did you have a chance to check out #57?

**Comment by tommymarshall** [comment]
Apologies, been jamming on client stuff. I'll give it a shot this afternoon!

**Comment by realityking** [comment]
@tommymarshall Hey Tommy, just circling back to this. Did you have a chance to test it? I'll merge it tomorrow.
