### ISSUE TITLE
Add ability to update Contentful's source CDN

### ISSUE THREAD

**Issue by tommymarshall** [contentful/contentful.php#55]
Probably crappy issue title, but it'd be great to able to customize the source URL of the CDN from which to fetch data.

### Use case
We're wary of hitting rate limits, so we'll periodically query content and cache the data on our end at a custom URL (our own CDN). I couldn't customize this library in an expected way (extend and override parent constructor) because variables were `private`.

### How I got around this
I copied and overrode [Contentful\Delivery\Client](https://github.com/contentful/contentful.php/blob/master/src/Delivery/Client.php#L64) and updated the base URI there.

### Possible solutions
1. Switch all `private` variables to `protected` so child Classes can override them (Refs #7)
1. Allow passing a custom URL to serve as a CDN (Added benefit of being able to easily stub data for testing)

### Proposed syntax for option 2
Pass a seventh (starting to get long, I know) parameter to override the base URI.
```php
new Client(config('contentful.token'), config('contentful.space'), config('contentful.preview'), null, null, 'en-US', 'https://cdn01.domain.com/spaces`);
```

### Disclaimer
I can see why this might be rejected, since we're technically grabbing this from a separate source which Contentful doesn't own, but can see how this might account for future custom regions/CDNs from Contentful.

**Comment by realityking** [comment]
Quick update on this: we will implement this using your option 2. Probably also going to change the signature to take an options array, even if that makes documenting the options a bit harder.

**Comment by realityking** [comment]
Fixed in current master. Thank you @tommymarshall for the suggestion :)
