### ISSUE TITLE
Field IDs with first letter uppercase don't work.

### ISSUE THREAD

**Issue by derpoho** [contentful/contentful.php#68]
If someone needs (or wants) to create field Ids with the first letter upopercase, this SDK will not work since here https://github.com/contentful/contentful.php/blob/master/src/Delivery/DynamicEntry.php#L94 the first letter will alway be converted to lowercase.

Two options come to my mind:

- Either Prepare the field Ids when they come so that the first letter is always lowercase.
- Extend the above line to handle Uppercase fieldIds too.

Edit: If someone wonders: Yes, you can create field Ids like this in Contentful: MetaDescription, PageTitle

Greets Marcus

**Comment by realityking** [comment]
Oh wow, that's a gigantic oversight. I'm not yet sure how we'll fix this :/

**Comment by derpoho** [comment]
It's really difficult since you can also create 3 fields in Contentful:
- firstName
- FirstName
- firstname

all 3 together are totally valid, so you never know if the user meant it to be uppercase oder not ;)
