### ISSUE TITLE
Trying to retrieve files with value "Id" as last two letters gets "Id" stripped of

### ISSUE THREAD

**Issue by sorenmalling** [contentful/contentful.php#9]
Trying to retrieve the value of a field with ex. DynamicEntry::getYoutubeId ends up looking for the field `youtube` and not `youtubeId`

This is due to line 82-85 

`
if (substr($fieldName, -2) === 'Id') {
            $fieldName = substr($fieldName, 0, -2);
            $getId = true;
        }
`

**Comment by realityking** [comment]
![](http://i2.kym-cdn.com/entries/icons/facebook/000/000/554/facepalm.jpg)

It never even occurred to me that people could name fields ***Id. Fix will come soon.

**Comment by realityking** [comment]
Thanks again for the report. The issue should now be fixed in master. The next release should be at the end of this or the beginning of next week.
