### ISSUE TITLE
Unset field throws error in src/Delivery/ResourceBuilder.php

### ISSUE THREAD

**Issue by spcherub** [contentful/contentful.php#99]
1. Create an asset (A), type in the title but do not attach a file. Save as draft
2. Associate this asset as a reference in another content item (B)
3. Use SDK to query for this item (B)
4. Exception thrown on line 208, triggered by call on line 189 where $fields['file'] is not set

**Comment by realityking** [comment]
Hi @spcherub,

Thanks for the bug report, I see how this happened. Just to clarify, this issue occurred when you used SDK with the preview API, didn't it?

**Comment by spcherub** [comment]
Yes preview API. I guess the normal workflow will not allow asset to be
published without the file attachment, so this won't happen with the
delivery API.
